### ISSUE TITLE
deployment fails on UK regions, but not on westeurope.

### ISSUE THREAD

**Issue by benavent** [Azure/uk-official-paas-webapp#4]
Hi,

I'm having problems deploying on the UK South and UK West regions.

The deployment fails with different errors in both regions.

Deployment to West Europe works without an issue.

Can anyone offer any advice?

 regards AndyW

**Comment by benavent** [comment]
Hi Ian,

Thank you very much for getting back to me.

Please find below the terminal output when running pre_reqs.sh for review.

Any assistance you can offer would be gratefully received.

Note, I have edited my logon to username@mydomain.co.uk. The original is the user id that the account was created by.

Regards

```
Andys-MacBook-Pro:ark_portal_sh Woody$ bash pre_reqs.sh uksouth arkportal rg-uks-paas-blueprint none pergb2018

Please enter a password for administering the deployed SQL Server, this should be at least 8 chars long and a mix of alhpanumeric and case:Password OK
Creating resource groups
Resource 'username@mydomain.co.uk' does not exist or one of its queried reference-property objects are not present.
Starting deployment...
Deployment failed. Correlation ID: c78a834e-3c11-4dd7-aa03-4807d0a383e1. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ProvisioningDisabled\",\r\n        \"message\": \"Provisioning is restricted in this region. Please choose a different region. For exceptions to this rule please contact Microsoft Support.\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
Deployment completed...
Script finished
Andys-MacBook-Pro:ark_portal_sh Woody$ 
```

A tidied up version of the error detail is:
```
status:Failed
error
	code:ResourceDeploymentFailure
	message:"The resource operation completed with terminal provisioning state 'Failed'.
	details:
		code:ProvisioningDisabled
		message:Provisioning is restricted in this region. Please choose a different region. For exceptions to this rule please contact Microsoft Support.
```

**Comment by ianalderman** [comment]
Hi Andy, having a look I wonder if this is down to the type of Subscription you are using to do the testing - is it a MSDN or free one by any chance?  The sub types are referred to as "offers" and as per the [region offer list](https://azure.microsoft.com/en-us/regions/offers/) the UK regions are not listed as available under the free / MSDN types, West Europe is listed - which fits with your experience.

**Comment by benavent** [comment]
Hi Ian,

Good point!

I believe that I have a full paid for account, although we are using invoice billing and not credit/charge card. (see image attached).

I wonder what Microsoft believes. Also, the account is under 12 months old, so still has access to some "free" services. I don't know what the impact of that might be.

I am going to raise a ticket with Azure support and see what they say.

I will post the results back to this thread.


<img width="722" alt="screenshot 2019-01-18 at 11 26 33" src="https://user-images.githubusercontent.com/16837199/51384499-6b991080-1b14-11e9-8423-8ca2a2af3ee8.png">

**Comment by benavent** [comment]
After leaving the last post I raised an issue with Azure support with the following contents:

>We are trying to install the PaaS Web Application Hosting for UK OFFICIAL Workloads bluprint on our subscription.
>It works when selecting the West Europe region, but not on the UK South or UK West regions.
>We have a requirement to only use UK based regions.

After some back and forth, in which I created a list of all resources to be created using Azure CLI, I got a email this afternoon containing the following:

>Capacity management team has approved the region enablement request for the UK South region for the subscription GUID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.

I have just tested it and the install against UK South worked without errors, as Ian said it would.
I'm note sure what they have changed, although I suspect it may have to do with Azure SQL Server.

Thank you Ian for your assistance.
I am closing this issue.
